### ISSUE TITLE
How to solve the program error? I hope to get your reply.

### ISSUE THREAD

**Issue by 15995118660** [TigerVersusT/matchNetPytorch#3]
# Found cached data ./data/phototour\liberty.pt
# Found cached data ./data/phototour\notredame.pt
Traceback (most recent call last):
  File "D:/Algorithm/compare_test/matchNetPytorch-main/train.py", line 212, in <module>
    main()
  File "D:/Algorithm/compare_test/matchNetPytorch-main/train.py", line 105, in main
    train(model, train_loader, criterion, optimizer, epoch)
  File "D:/Algorithm/compare_test/matchNetPytorch-main/train.py", line 169, in train
    for i, (data1, data2, matches) in enumerate(trainLoader):
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 368, in __iter__
    return self._get_iterator()
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 927, in __init__
    w.start()
  File "D:\Anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.preporcessing'

**Comment by Zsynapsis** [comment]
我也遇到了这个问题，还没有解决
